name: Feature Requests
description: Features, mods and suggestions for modpacks
body:
  - type: dropdown
    id: modpack-list
    attributes:
      label: Modpack
      description: What modpack would you like to tweak
      multiple: false
      options:
        - Desertopolis
        - Stoneopolis
        - Aeropolis
        - Omniopolis
        - Techopolis
        - Techopolis 2
        - Skyopolis 
        - Skyopolis 2
        - Skyopolis 3
        - Skyopolis 4
        - Skyopolis 5
        - Seaopolis
        - Seaopolis 2
        - Other...
    validations:
      required: true
  - type: textarea
    id: bugdesc
    attributes:
      label: Describe the feature, mod or suggestion
      description: |
        What this adds
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the feature, mod or suggestion
    validations:
      required: false
